<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.17" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.27" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CraftIQ.Inventory.Shared\CraftIQ.Inventory.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Inventories\Queries\Result\" />
    <Folder Include="Features\OrderDetail\Queries\Result\" />
    <Folder Include="Features\Orders\Queries\Result\" />
    <Folder Include="Features\Products\Queries\Result\" />
    <Folder Include="Features\Transactions\Queries\Result\" />
  </ItemGroup>

</Project>
